[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

# [colors.normal]
# blue = "#b59a74"
# green = "#118822"
# white = "#ffffff"

[colors.primary]
# mf era?
# background = "#09122e"
# background = "#0a1533"
# background = "#0e1b42"

# background = "#131e26" # green from focus editor
# pf era 
# background = "#00001A"

# background = "#010105"
# background = "#555555"

[debug]
log_level = "Info"
persistent_logging = true
print_events = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 13.0

[font.offset]
y = 2

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "p"
mods = "Alt"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/bash"

[general]
# [general]
#import = ["~/.config/alacritty/themes/themes/kimbie_dark.toml"]

[window]
opacity = 0.8

[terminal]

