#!/bin/sh

# Monitor and desktop layout
~/.config/bspwm/monitors.sh &

# Настройка рабочих столов для мониторов
bspc monitor DP-4 -d 4 5 6             # Left monitor
bspc monitor DP-2 -d 1 2 3             # Center (primary) monitor
bspc monitor DP-0 -d 7 8 9             # Right monitor

# Внешний вид окон
bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# Отступ сверху для Polybar
bspc config -m DP-4 top_padding 30
bspc config -m DP-2 top_padding 30
bspc config -m DP-0 top_padding 30

~/.config/bspwm/autostart.sh &
